# -*- coding: utf-8 -*-
"""Copy of SIH.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yb0CsLXudiNSPCDjF78fThr2kYtGTLZ9
"""

# ================================================================
# INDUSTRIAL FIRE AI — FULL PIPELINE (TAMIL NADU)
#
# Run this in a fresh Colab notebook. Only requirement:
#   A NASA FIRMS ZIP export sitting in your Google Drive root
#   (My Drive), containing the three CSVs:
#     fire_nrt_J1V-C2_*.csv   (VIIRS N20)
#     fire_nrt_SV-C2_*.csv    (VIIRS Suomi-NPP)
#     fire_nrt_M-C61_*.csv    (MODIS — excluded from analysis)
#
# WHAT THIS DOES:
#   1. Loads + cleans FIRMS VIIRS data (N20 + Suomi-NPP; MODIS excluded)
#   2. Filters to the REAL Tamil Nadu polygon (not a bounding box)
#   3. Pulls OSM industrial facilities for that area
#   4. Spatially joins fires to nearest facility
#   5. Engineers temporal / thermal / per-location-anomaly features
#   6. Samples ESA WorldCover land cover at each fire point (optional,
#      degrades gracefully if you skip Earth Engine setup)
#   7. Builds weak (heuristic) fire-type labels
#   8. Trains a classifier to distinguish industrial fires / persistent
#      thermal sources / forest fires / agricultural burning
#   9. Exports a classified CSV, GeoJSON, and an interactive HTML map
#
# You can run this as one script, or split at the "# --- CELL n ---"
# markers into separate Colab cells.
# ================================================================


# --- CELL 1: SETUP -------------------------------------------------

import os
import json
import zipfile
import warnings
import requests
import numpy as np
import pandas as pd
import geopandas as gpd

from pathlib import Path
from google.colab import drive

warnings.filterwarnings("ignore")

print("=" * 70)
print("INDUSTRIAL FIRE AI PIPELINE — TAMIL NADU")
print("=" * 70)

drive.mount("/content/drive", force_remount=False)

PROJECT_DIR = Path("/content/drive/MyDrive/IndustrialFireAI_TN")
CACHE_DIR = PROJECT_DIR / "cache"
PROJECT_DIR.mkdir(parents=True, exist_ok=True)
CACHE_DIR.mkdir(parents=True, exist_ok=True)

print("\nProject directory:", PROJECT_DIR)
print("Cache directory:", CACHE_DIR)


# --- CELL 2: FIND + EXTRACT NASA FIRMS ZIP --------------------------

print("\n" + "=" * 70)
print("SEARCHING FOR NASA FIRMS ZIP")
print("=" * 70)

zip_files = list(Path("/content/drive/MyDrive").glob("*.zip"))
if len(zip_files) == 0:
    raise FileNotFoundError("No ZIP file found in Google Drive root (My Drive).")

print("ZIP files found:")
for i, z in enumerate(zip_files):
    print(f"[{i}] {z} ({z.stat().st_size / (1024*1024):.2f} MB)")

preferred = [z for z in zip_files if z.name.lower() == "archive.zip"]
FIRMS_ZIP = preferred[0] if preferred else max(zip_files, key=lambda x: x.stat().st_size)
print("\nSelected FIRMS ZIP:", FIRMS_ZIP)

EXTRACT_DIR = CACHE_DIR / "firms_extracted"
EXTRACT_DIR.mkdir(parents=True, exist_ok=True)

existing_csvs = list(EXTRACT_DIR.glob("*.csv"))
if len(existing_csvs) >= 3:
    print("Cached extraction found.")
else:
    print("Extracting FIRMS ZIP...")
    with zipfile.ZipFile(FIRMS_ZIP, "r") as z:
        z.extractall(EXTRACT_DIR)
    print("Extraction completed.")

csv_files = list(EXTRACT_DIR.rglob("*.csv"))
print(f"\nCSV files found: {len(csv_files)}")
for f in csv_files:
    print(f"{f.name} | {f.stat().st_size / (1024*1024):.2f} MB")

n20_files = [f for f in csv_files if "J1V-C2" in f.name.upper()]
npp_files = [f for f in csv_files if "SV-C2" in f.name.upper()]
modis_files = [f for f in csv_files if "M-C61" in f.name.upper()]

if not n20_files:
    raise RuntimeError("VIIRS N20 FIRMS file not found.")
if not npp_files:
    raise RuntimeError("VIIRS Suomi-NPP FIRMS file not found.")

N20_FILE, NPP_FILE = n20_files[0], npp_files[0]
print("\nVIIRS N20:", N20_FILE.name)
print("VIIRS Suomi-NPP:", NPP_FILE.name)
print("MODIS — EXCLUDED:", [f.name for f in modis_files])


# --- CELL 3: LOAD + CLEAN VIIRS -------------------------------------

print("\n" + "=" * 70)
print("LOADING + CLEANING VIIRS DATA")
print("=" * 70)

VIIRS_CACHE = CACHE_DIR / "VIIRS_primary_clean.csv"

if VIIRS_CACHE.exists():
    print("Loading cached VIIRS dataset...")
    viirs = pd.read_csv(VIIRS_CACHE, low_memory=False)
else:
    n20 = pd.read_csv(N20_FILE, low_memory=False)
    n20["satellite_source"] = "VIIRS_N20"

    npp = pd.read_csv(NPP_FILE, low_memory=False)
    npp["satellite_source"] = "VIIRS_SUOMI_NPP"

    viirs = pd.concat([n20, npp], ignore_index=True)
    del n20, npp

    print("Combined VIIRS rows:", f"{len(viirs):,}")

    # Clean
    before = len(viirs)
    numeric_cols = ["latitude", "longitude", "brightness", "scan", "track", "bright_t31", "frp"]
    for col in numeric_cols:
        if col in viirs.columns:
            viirs[col] = pd.to_numeric(viirs[col], errors="coerce")

    viirs["acq_date"] = pd.to_datetime(viirs["acq_date"], errors="coerce")
    viirs = viirs[viirs["latitude"].between(-90, 90) & viirs["longitude"].between(-180, 180)]
    viirs = viirs.dropna(subset=["latitude", "longitude", "acq_date", "brightness", "frp"])
    viirs = viirs.drop_duplicates().reset_index(drop=True)

    print("Rows before cleaning:", f"{before:,}")
    print("Rows after cleaning:", f"{len(viirs):,}")

    viirs.to_csv(VIIRS_CACHE, index=False)
    print("Cached cleaned VIIRS dataset.")

# Hard safety check (FIX: was a soft warning before, now a real assert)
sat_values = viirs["satellite_source"].astype(str).unique()
assert "VIIRS_N20" in sat_values, "N20 missing from dataset."
assert "VIIRS_SUOMI_NPP" in sat_values, "Suomi-NPP missing from dataset."
assert not any("MODIS" in str(x).upper() for x in sat_values), "MODIS leaked into dataset."
print("Satellite safety check (hard assert): PASSED")


# --- CELL 4: TAMIL NADU BOUNDARY (real polygon, not a bbox) ---------

print("\n" + "=" * 70)
print("GETTING TAMIL NADU BOUNDARY")
print("=" * 70)

TN_CACHE = CACHE_DIR / "tamil_nadu_boundary.geojson"

if TN_CACHE.exists():
    tn = gpd.read_file(TN_CACHE)
    print("Loaded cached Tamil Nadu boundary.")
else:
    NE_URL = (
        "https://naturalearth.s3.amazonaws.com/"
        "10m_cultural/ne_10m_admin_1_states_provinces.zip"
    )
    ne_zip = CACHE_DIR / "ne_admin1.zip"
    r = requests.get(NE_URL, timeout=180)
    print("HTTP:", r.status_code)
    r.raise_for_status()
    ne_zip.write_bytes(r.content)

    ne_extract = CACHE_DIR / "ne_admin1"
    ne_extract.mkdir(exist_ok=True)
    with zipfile.ZipFile(ne_zip, "r") as z:
        z.extractall(ne_extract)

    shp_files = list(ne_extract.rglob("*.shp"))
    if not shp_files:
        raise RuntimeError("Natural Earth admin-1 shapefile not found.")

    states = gpd.read_file(shp_files[0])
    name_col = next((c for c in ["name", "NAME", "woe_name", "gn_name"] if c in states.columns), None)
    if name_col is None:
        raise RuntimeError("Could not identify state-name column.")

    tn = states[states[name_col].astype(str).str.lower() == "tamil nadu"].copy()
    if tn.empty:
        raise RuntimeError("Tamil Nadu polygon not found — check admin-1 name values.")

    tn = tn.to_crs("EPSG:4326")
    tn.to_file(TN_CACHE, driver="GeoJSON")
    print("Tamil Nadu polygon found and cached.")

tn = tn.to_crs("EPSG:4326")
TN_MINX, TN_MINY, TN_MAXX, TN_MAXY = tn.total_bounds
print(f"Tamil Nadu bounds: lon [{TN_MINX:.2f}, {TN_MAXX:.2f}], lat [{TN_MINY:.2f}, {TN_MAXY:.2f}]")


# --- CELL 5: FILTER VIIRS TO TAMIL NADU POLYGON ---------------------

print("\n" + "=" * 70)
print("FILTERING VIIRS TO TAMIL NADU POLYGON")
print("=" * 70)

bbox_mask = viirs["longitude"].between(TN_MINX, TN_MAXX) & viirs["latitude"].between(TN_MINY, TN_MAXY)
tn_candidates = viirs[bbox_mask].copy()
print("Bounding-box candidates:", f"{len(tn_candidates):,}")

points = gpd.GeoDataFrame(
    tn_candidates,
    geometry=gpd.points_from_xy(tn_candidates["longitude"], tn_candidates["latitude"]),
    crs="EPSG:4326",
)
tn_union = tn.geometry.union_all()
inside = points.geometry.within(tn_union)

study = points[inside].drop(columns=["geometry"]).reset_index(drop=True)
print("ACTUAL TAMIL NADU DETECTIONS:", f"{len(study):,}")
print("Removed by polygon test:", f"{len(tn_candidates) - len(study):,}")

if len(study) == 0:
    raise RuntimeError("No detections found inside Tamil Nadu polygon.")

STUDY_FILE = PROJECT_DIR / "Study_Region_TamilNadu_VIIRS.csv"
study.to_csv(STUDY_FILE, index=False)
print("Saved:", STUDY_FILE)


# --- CELL 6: OSM INDUSTRIAL FACILITIES (Tamil Nadu bbox) ------------


import time

print("\n" + "=" * 70)
print("DOWNLOADING OSM INDUSTRIAL FACILITIES")
print("=" * 70)

OSM_JSON = CACHE_DIR / "osm_industrial_facilities.json"
OSM_CSV = PROJECT_DIR / "OSM_Industrial_Facilities.csv"

OVERPASS_MIRRORS = [
    "https://overpass-api.de/api/interpreter",
    "https://overpass.kumi.systems/api/interpreter",
    "https://overpass.openstreetmap.ru/api/interpreter",
    "https://overpass.private.coffee/api/interpreter",
]

TAG_QUERIES = {
    "power_plant": f'nwr["power"="plant"]({TN_MINY},{TN_MINX},{TN_MAXY},{TN_MAXX});',
    "man_made_works": f'nwr["man_made"="works"]({TN_MINY},{TN_MINX},{TN_MAXY},{TN_MAXX});',
    "industrial": f'nwr["industrial"]({TN_MINY},{TN_MINX},{TN_MAXY},{TN_MAXX});',
}

headers = {"User-Agent": "IndustrialFireAI/1.0"}


def run_overpass_query(tag_clause, max_retries=2):
    """Try each mirror, with a couple of retries per mirror, before giving up."""
    query = f"[out:json][timeout:60];\n({tag_clause});\nout center;"

    for mirror in OVERPASS_MIRRORS:
        for attempt in range(max_retries):
            try:
                print(f"  Trying {mirror} (attempt {attempt + 1})...")
                resp = requests.get(
                    mirror, params={"data": query}, headers=headers, timeout=90
                )
                if resp.status_code == 200:
                    data = resp.json()
                    n = len(data.get("elements", []))
                    print(f"  Success: {n} elements")
                    return data.get("elements", [])
                else:
                    print(f"  HTTP {resp.status_code} from {mirror}")
            except Exception as e:
                print(f"  Failed on {mirror}: {e}")
            time.sleep(5)  # brief backoff before retry/next mirror
    return None


if OSM_JSON.exists():
    print("Cached OSM data found.")
    with open(OSM_JSON, "r", encoding="utf-8") as f:
        osm_data = json.load(f)
    elements = osm_data.get("elements", [])
else:
    print("Querying Overpass mirrors (split into 3 smaller queries)...")

    all_elements = []
    seen_ids = set()

    for tag_name, clause in TAG_QUERIES.items():
        print(f"\nQuery: {tag_name}")
        result = run_overpass_query(clause)
        if result is None:
            print(f"  WARNING: all mirrors failed for '{tag_name}' — skipping this tag.")
            continue
        for el in result:
            key = (el.get("type"), el.get("id"))
            if key not in seen_ids:
                seen_ids.add(key)
                all_elements.append(el)

    if len(all_elements) == 0:
        raise RuntimeError(
            "OSM query returned zero elements from all mirrors and all tags. "
            "Overpass may be fully down right now — wait a few minutes and rerun "
            "this cell (it will pick up from here since earlier cells are cached)."
        )

    osm_data = {"elements": all_elements}
    elements = all_elements

    with open(OSM_JSON, "w", encoding="utf-8") as f:
        json.dump(osm_data, f)
    print(f"\nOSM raw data cached: {OSM_JSON} ({len(elements)} total elements)")

facility_records = []

for element in elements:
    tags = element.get("tags", {})
    if element.get("type") == "node":
        lat, lon = element.get("lat"), element.get("lon")
    else:
        center = element.get("center", {})
        lat, lon = center.get("lat"), center.get("lon")
    if lat is None or lon is None:
        continue

    power = str(tags.get("power", "")).lower()
    industrial = str(tags.get("industrial", "")).lower()
    man_made = str(tags.get("man_made", "")).lower()

    facility_type = "Other Industrial"
    if power == "plant":
        facility_type = "Power Plant"
    elif industrial in ["factory", "manufacture", "manufacturing", "industrial"]:
        facility_type = "Manufacturing"
    elif industrial in ["warehouse", "depot", "logistics"]:
        facility_type = "Warehouse/Depot"
    elif industrial in ["oil", "gas", "petroleum"]:
        facility_type = "Oil & Gas"
    elif industrial in ["chemical", "chemicals"]:
        facility_type = "Chemical"
    elif industrial in ["mine", "mining", "quarry"]:
        facility_type = "Mining"
    elif industrial in ["cement", "construction_materials", "bricks", "stone"]:
        facility_type = "Construction Materials"
    elif industrial in ["shipyard", "port"]:
        facility_type = "Port/Shipyard"
    elif man_made == "works":
        facility_type = "Industrial Works"

    facility_records.append({
        "osm_id": element.get("id"),
        "osm_type": element.get("type"),
        "latitude": float(lat),
        "longitude": float(lon),
        "name": str(tags.get("name", "")),
        "operator": str(tags.get("operator", "")),
        "facility_type": facility_type,
    })

osm_df = pd.DataFrame(facility_records)
if not osm_df.empty:
    osm_df = osm_df.drop_duplicates(subset=["osm_type", "osm_id"]).reset_index(drop=True)

print("\nUnique OSM facilities:", f"{len(osm_df):,}")
print("\nFacility categories:")
print(osm_df["facility_type"].value_counts())

osm_df.to_csv(OSM_CSV, index=False)
print("\nSaved:", OSM_CSV)

if len(osm_df) == 0:
    raise RuntimeError("No OSM facilities available for Tamil Nadu.")



# --- CELL 7: SPATIAL JOIN (fires <-> nearest facility) --------------

print("\n" + "=" * 70)
print("MATCHING FIRE DETECTIONS WITH NEAREST FACILITY")
print("=" * 70)

study_gdf = gpd.GeoDataFrame(
    study.copy(), geometry=gpd.points_from_xy(study["longitude"], study["latitude"]), crs="EPSG:4326"
)
osm_gdf = gpd.GeoDataFrame(
    osm_df.copy(), geometry=gpd.points_from_xy(osm_df["longitude"], osm_df["latitude"]), crs="EPSG:4326"
)

study_metric = study_gdf.to_crs("EPSG:32643")  # UTM 43N — valid for Tamil Nadu
osm_metric = osm_gdf.to_crs("EPSG:32643")

n_before_join = len(study_metric)

nearest = gpd.sjoin_nearest(
    study_metric,
    osm_metric[["osm_id", "osm_type", "facility_type", "name", "operator", "geometry"]],
    how="left",
    distance_col="distance_to_facility_m",
)

# FIX: explicit duplicate-row check instead of trusting sjoin_nearest silently
if len(nearest) != n_before_join:
    print(
        f"WARNING: sjoin_nearest returned {len(nearest):,} rows from "
        f"{n_before_join:,} input points (tied-distance duplicates). "
        "Keeping first match per point."
    )
    nearest = nearest[~nearest.index.duplicated(keep="first")]

assert len(nearest) == n_before_join, "Row count mismatch after spatial join — investigate."
print("Spatial join row-count check: PASSED", f"({len(nearest):,} rows)")

features = nearest.copy()


# --- CELL 8: FEATURE ENGINEERING ------------------------------------

print("\n" + "=" * 70)
print("ENGINEERING FEATURES")
print("=" * 70)

# Facility distance features
for radius in [500, 1000, 2000, 5000]:
    features[f"near_industrial_{radius}m"] = (features["distance_to_facility_m"] <= radius).astype(int)

features["distance_to_facility_km"] = features["distance_to_facility_m"] / 1000.0
features["industrial_facility_present"] = features["distance_to_facility_m"].notna().astype(int)

facility_map = {
    "Power Plant": 1, "Industrial Works": 2, "Manufacturing": 3,
    "Warehouse/Depot": 4, "Construction Materials": 5, "Port/Shipyard": 6,
    "Oil & Gas": 7, "Mining": 8, "Chemical": 9, "Other Industrial": 10,
}
features["facility_type_code"] = features["facility_type"].map(facility_map).fillna(0).astype(int)

# Temporal features
features["acq_date"] = pd.to_datetime(features["acq_date"], errors="coerce")
features["day_of_year"] = features["acq_date"].dt.dayofyear
features["month"] = features["acq_date"].dt.month
features["year"] = features["acq_date"].dt.year
features["acq_time_numeric"] = pd.to_numeric(features["acq_time"], errors="coerce")
features["hour"] = features["acq_time_numeric"].fillna(0).astype(int) // 100

if "daynight" in features.columns:
    features["is_day"] = features["daynight"].astype(str).str.upper().eq("D").astype(int)
else:
    features["is_day"] = 0

# Thermal features
features["brightness_difference"] = features["brightness"] - features["bright_t31"]
features["frp_brightness_ratio"] = features["frp"] / features["brightness"].replace(0, np.nan)
features["log_frp"] = np.log1p(features["frp"].clip(lower=0))

def confidence_encode(x):
    x = str(x).lower().strip()
    if x == "h":
        return 2
    if x == "l":
        return 0
    if x == "n":
        return 1
    try:
        return float(x)
    except Exception:
        return 1

features["confidence_numeric"] = features["confidence"].apply(confidence_encode)
features["is_n20"] = features["satellite_source"].eq("VIIRS_N20").astype(int)
features["is_suomi_npp"] = features["satellite_source"].eq("VIIRS_SUOMI_NPP").astype(int)

# Seasonal windows (India-specific, weak-label signal only)
features["is_forest_fire_season"] = features["month"].isin([2, 3, 4, 5]).astype(int)
features["is_stubble_burning_season"] = features["month"].isin([10, 11, 4, 5]).astype(int)

# Spatial grid (~1km)
GRID_SIZE = 0.01
features["grid_lat"] = np.floor(features["latitude"] / GRID_SIZE) * GRID_SIZE
features["grid_lon"] = np.floor(features["longitude"] / GRID_SIZE) * GRID_SIZE
features["grid_id"] = (
    features["grid_lat"].round(4).astype(str) + "_" + features["grid_lon"].round(4).astype(str)
)

grid_counts = features.groupby("grid_id").size().rename("grid_detection_count")
grid_days = features.groupby("grid_id")["acq_date"].nunique().rename("grid_active_days")
grid_frp = features.groupby("grid_id")["frp"].sum().rename("grid_total_frp")
features = features.merge(grid_counts, on="grid_id", how="left")
features = features.merge(grid_days, on="grid_id", how="left")
features = features.merge(grid_frp, on="grid_id", how="left")

# FIX: per-grid (location-relative) z-scores instead of global-only.
# A facility that's always hot shouldn't look anomalous vs the whole
# dataset — it should only flag when it's hot relative to ITS OWN history.
MIN_GRID_OBS = 5

grid_stats = features.groupby("grid_id").agg(
    grid_brightness_mean=("brightness", "mean"),
    grid_brightness_std=("brightness", "std"),
    grid_frp_mean=("frp", "mean"),
    grid_frp_std=("frp", "std"),
    grid_n=("brightness", "count"),
).reset_index()
features = features.merge(grid_stats, on="grid_id", how="left")

global_brightness_mean, global_brightness_std = features["brightness"].mean(), features["brightness"].std()
global_frp_mean, global_frp_std = features["frp"].mean(), features["frp"].std()
enough_history = features["grid_n"] >= MIN_GRID_OBS

features["brightness_zscore_local"] = np.where(
    enough_history & (features["grid_brightness_std"] > 0),
    (features["brightness"] - features["grid_brightness_mean"]) / features["grid_brightness_std"],
    (features["brightness"] - global_brightness_mean) / global_brightness_std,
)
features["frp_zscore_local"] = np.where(
    enough_history & (features["grid_frp_std"] > 0),
    (features["frp"] - features["grid_frp_mean"]) / features["grid_frp_std"],
    (features["frp"] - global_frp_mean) / global_frp_std,
)
features["used_local_baseline"] = enough_history.astype(int)
features["high_brightness_flag_local"] = (features["brightness_zscore_local"] >= 2).astype(int)
features["high_frp_flag_local"] = (features["frp_zscore_local"] >= 2).astype(int)
features["persistent_location_flag"] = (features["grid_active_days"] >= 3).astype(int)

print("Feature engineering complete. Columns:", len(features.columns))

# --- CELL 9 (NO-AUTH VERSION): LAND COVER (ESA WorldCover, direct S3) --
#
# This replaces the Google Earth Engine approach entirely — no login,
# no browser flow, no verification code needed.
#
# HOW IT WORKS:
# ESA WorldCover tiles are hosted as public, unauthenticated Cloud-
# Optimized GeoTIFFs on AWS S3. Using GDAL's "/vsicurl/" virtual file
# system, rasterio can read just the specific pixels under each of
# your fire points via HTTP range requests — it does NOT download
# the full tile (each tile covers 3x3 degrees and would be large).
#
# Requirements: rasterio (usually preinstalled in Colab; the pip
# line below is a no-op if it's already there).
# ---------------------------------------------------------------

print("\n" + "=" * 70)
print("SAMPLING LAND COVER (ESA WORLDCOVER — direct S3, no auth)")
print("=" * 70)

import subprocess
subprocess.run(["pip", "install", "-q", "rasterio"], check=False)

import rasterio

LANDCOVER_CACHE = CACHE_DIR / "landcover_tn_sampled.csv"

WORLDCOVER_CLASS_MAP = {
    10: "Tree cover", 20: "Shrubland", 30: "Grassland", 40: "Cropland",
    50: "Built-up", 60: "Bare/sparse vegetation", 70: "Snow and ice",
    80: "Permanent water bodies", 90: "Herbaceous wetland",
    95: "Mangroves", 100: "Moss and lichen",
}

WORLDCOVER_BASE_URL = (
    "https://esa-worldcover.s3.eu-central-1.amazonaws.com/v200/2021/map/"
    "ESA_WorldCover_10m_2021_v200_{tile}_Map.tif"
)


def worldcover_tile_name(lat, lon):
    """ESA WorldCover tiles are named by their 3x3-degree lower-left corner."""
    lat_tile = int(np.floor(lat / 3.0) * 3)
    lon_tile = int(np.floor(lon / 3.0) * 3)
    ns = "N" if lat_tile >= 0 else "S"
    ew = "E" if lon_tile >= 0 else "W"
    return f"{ns}{abs(lat_tile):02d}{ew}{abs(lon_tile):03d}"


landcover_available = False

if LANDCOVER_CACHE.exists():
    print("Loading cached land-cover sample.")
    lc_df = pd.read_csv(LANDCOVER_CACHE)
    landcover_available = True
else:
    try:
        coords = features[["latitude", "longitude"]].reset_index(drop=True)
        coords["tile"] = coords.apply(
            lambda r: worldcover_tile_name(r["latitude"], r["longitude"]), axis=1
        )

        unique_tiles = coords["tile"].unique()
        print(f"Points span {len(unique_tiles)} WorldCover tile(s): {list(unique_tiles)}")

        results = {}

        for tile in unique_tiles:
            url = "/vsicurl/" + WORLDCOVER_BASE_URL.format(tile=tile)
            print(f"\nReading tile {tile} via remote range-read (no full download)...")

            tile_points = coords[coords["tile"] == tile]

            try:
                with rasterio.open(url) as src:
                    sample_coords = list(zip(tile_points["longitude"], tile_points["latitude"]))
                    values = list(src.sample(sample_coords))
                    for idx, val in zip(tile_points.index, values):
                        results[idx] = int(val[0]) if val is not None else np.nan
                print(f"  Sampled {len(tile_points)} points from {tile}")
            except Exception as tile_err:
                print(f"  WARNING: could not read tile {tile}: {tile_err}")
                for idx in tile_points.index:
                    results[idx] = np.nan

        lc_df = pd.DataFrame({
            "row_id": list(results.keys()),
            "landcover_code": list(results.values()),
        }).sort_values("row_id").reset_index(drop=True)

        lc_df.to_csv(LANDCOVER_CACHE, index=False)
        print("\nLand-cover sample cached:", LANDCOVER_CACHE)
        landcover_available = True

    except Exception as e:
        print("Direct S3 land-cover sampling failed:", e)
        print("Continuing WITHOUT land cover — weak labels will fall back to")
        print("facility-distance + thermal-anomaly rules only (next cell handles this).")
        lc_df = pd.DataFrame({"row_id": range(len(features)), "landcover_code": [np.nan] * len(features)})

features = features.reset_index(drop=True)
features["row_id"] = features.index
features = features.merge(lc_df, on="row_id", how="left")
features["landcover_class"] = features["landcover_code"].map(WORLDCOVER_CLASS_MAP).fillna("Unknown")

print("\nLand cover distribution:")
print(features["landcover_class"].value_counts())
print("\nLand cover available:", landcover_available)


# --- CELL 10 (FIXED): WEAK LABELS + CLASSIFIER ----------------------
#
# FIX: the previous version required a specific land-cover match
# (Built-up / Tree cover / Cropland) to assign ANY class other than
# "Other/Unclassified". If land cover is unavailable, every row fell
# into one bucket — a degenerate, unlearnable target (which is what
# happened in your run: 634/634 "Other/Unclassified").
#
# This version uses land cover as a REFINEMENT when available, but
# falls back to facility-distance + persistence + thermal-anomaly
# rules alone when it isn't — so the classifier always has a real,
# non-degenerate multi-class target to learn from.
# ---------------------------------------------------------------

print("\n" + "=" * 70)
print("BUILDING WEAK LABELS")
print("=" * 70)

def assign_weak_label(row):
    near_facility = row["distance_to_facility_m"] <= 2000
    persistent = row["grid_active_days"] >= 3
    local_spike = (row["high_brightness_flag_local"] == 1) or (row["high_frp_flag_local"] == 1)

    has_landcover = row["landcover_class"] != "Unknown"
    built_up = row["landcover_class"] == "Built-up"
    forest = row["landcover_class"] == "Tree cover"
    cropland = row["landcover_class"] == "Cropland"

    if has_landcover:
        # Stricter rules when we know the land cover
        if near_facility and built_up and persistent and not local_spike:
            return "Persistent Thermal Source"
        if near_facility and built_up and local_spike:
            return "Industrial Fire"
        if forest and not near_facility and row["is_forest_fire_season"] == 1:
            return "Forest Fire"
        if cropland and not persistent and row["is_stubble_burning_season"] == 1:
            return "Agricultural Burning"
        return "Other/Unclassified"
    else:
        # FALLBACK: no land cover — use facility distance + persistence +
        # thermal anomaly + season only. Less precise, but non-degenerate.
        if near_facility and persistent and not local_spike:
            return "Persistent Thermal Source"
        if near_facility and local_spike:
            return "Industrial Fire"
        if not near_facility and local_spike and row["is_forest_fire_season"] == 1:
            return "Possible Forest Fire"
        if not near_facility and not persistent and row["is_stubble_burning_season"] == 1:
            return "Possible Agricultural Burning"
        return "Other/Unclassified"

features["weak_label"] = features.apply(assign_weak_label, axis=1)
print("\nWeak label distribution:")
print(features["weak_label"].value_counts())

if features["weak_label"].nunique() == 1:
    print(
        "\nWARNING: all rows fell into a single class even with the fallback "
        "rules. This usually means near_facility/persistent/local_spike are "
        "themselves degenerate (e.g. distance_to_facility_m is NaN for "
        "everything, or grid_active_days is 1 for everything). Check those "
        "columns before training — a classifier cannot learn from one class."
    )
else:
    print(
        "\nNOTE: these are heuristic labels, not ground truth — and the "
        "fallback (no-land-cover) rules are weaker than the land-cover-aware "
        "ones. Spot-check a sample from each class against known real "
        "incidents before trusting the model operationally. Strongly "
        "recommend fixing GEE auth (Cell 9) and rerunning for better labels."
    )

print("\n" + "=" * 70)
print("TRAINING CLASSIFIER")
print("=" * 70)

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

MODEL_FEATURES = [
    "brightness", "bright_t31", "frp", "scan", "track",
    "brightness_difference", "frp_brightness_ratio", "log_frp",
    "confidence_numeric", "is_n20", "is_suomi_npp", "is_day", "hour",
    "month", "day_of_year",
    "distance_to_facility_km", "industrial_facility_present", "facility_type_code",
    "near_industrial_500m", "near_industrial_1000m", "near_industrial_2000m", "near_industrial_5000m",
    "grid_detection_count", "grid_active_days", "grid_total_frp",
    "brightness_zscore_local", "frp_zscore_local", "used_local_baseline",
    "is_forest_fire_season", "is_stubble_burning_season",
    "landcover_code",
]

model_df = features.dropna(subset=["weak_label"]).copy()
model_df[MODEL_FEATURES] = model_df[MODEL_FEATURES].apply(pd.to_numeric, errors="coerce")
model_df[MODEL_FEATURES] = model_df[MODEL_FEATURES].fillna(model_df[MODEL_FEATURES].median())

X = model_df[MODEL_FEATURES]
y = model_df["weak_label"]

print("\nClass balance going into training:")
print(y.value_counts())

if y.nunique() < 2:
    raise RuntimeError(
        "Only one class present in weak labels — cannot train a classifier. "
        "See the WARNING above for what to check."
    )

# Guard against classes too small to stratify/split
min_class_count = y.value_counts().min()
can_stratify = min_class_count >= 2

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42, stratify=y if can_stratify else None
)

clf = RandomForestClassifier(
    n_estimators=300, max_depth=12, min_samples_leaf=3,
    class_weight="balanced", random_state=42, n_jobs=-1,
)
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
print("\nClassification report (held-out test set):")
print(classification_report(y_test, y_pred, zero_division=0))

importances = pd.Series(clf.feature_importances_, index=MODEL_FEATURES).sort_values(ascending=False)
print("\nTop 10 feature importances:")
print(importances.head(10))

X_all = features[MODEL_FEATURES].apply(pd.to_numeric, errors="coerce").fillna(X.median())
features["predicted_class"] = clf.predict(X_all)
features["predicted_class_confidence"] = clf.predict_proba(X_all).max(axis=1)


# --- CELL 11: SAVE OUTPUTS + GIS MAP --------------------------------

print("\n" + "=" * 70)
print("SAVING OUTPUTS")
print("=" * 70)

features_out = features.replace([np.inf, -np.inf], np.nan)

PHASE_FILE = PROJECT_DIR / "TamilNadu_Classified_Fires.csv"
features_out.to_csv(PHASE_FILE, index=False)
print("Saved:", PHASE_FILE)

geo_out = gpd.GeoDataFrame(
    features_out,
    geometry=gpd.points_from_xy(features_out["longitude"], features_out["latitude"]),
    crs="EPSG:4326",
)
GEOJSON_FILE = PROJECT_DIR / "TamilNadu_Classified_Fires.geojson"
geo_out.to_file(GEOJSON_FILE, driver="GeoJSON")
print("Saved:", GEOJSON_FILE)

import folium
from folium.plugins import MarkerCluster

CLASS_COLORS = {
    "Persistent Thermal Source": "orange",
    "Industrial Fire": "red",
    "Forest Fire": "darkgreen",
    "Agricultural Burning": "goldenrod",
    "Other/Unclassified": "gray",
}

m = folium.Map(
    location=[features_out["latitude"].mean(), features_out["longitude"].mean()],
    zoom_start=7, tiles="CartoDB positron",
)

fire_layers = {cls: folium.FeatureGroup(name=f"Fires: {cls}") for cls in features_out["predicted_class"].unique()}
for _, row in features_out.iterrows():
    cls = row["predicted_class"]
    folium.CircleMarker(
        location=[row["latitude"], row["longitude"]],
        radius=4, color=CLASS_COLORS.get(cls, "black"), fill=True, fill_opacity=0.7,
        popup=folium.Popup(
            f"<b>{cls}</b><br>Date: {row['acq_date']}<br>FRP: {row['frp']}<br>"
            f"Brightness: {row['brightness']}<br>Land cover: {row['landcover_class']}<br>"
            f"Nearest facility: {row.get('name', 'N/A')} ({row.get('facility_type', 'N/A')})<br>"
            f"Distance: {row['distance_to_facility_km']:.2f} km<br>"
            f"Confidence: {row['predicted_class_confidence']:.2f}",
            max_width=300,
        ),
    ).add_to(fire_layers[cls])
for layer in fire_layers.values():
    layer.add_to(m)

facility_layer = folium.FeatureGroup(name="OSM Industrial Facilities")
facility_cluster = MarkerCluster().add_to(facility_layer)
for _, row in osm_df.iterrows():
    folium.Marker(
        location=[row["latitude"], row["longitude"]],
        icon=folium.Icon(color="blue", icon="industry", prefix="fa"),
        popup=f"{row.get('name', 'Unnamed')} ({row['facility_type']})",
    ).add_to(facility_cluster)
facility_layer.add_to(m)

folium.GeoJson(
    tn.to_json(), name="Tamil Nadu Boundary",
    style_function=lambda x: {"fillOpacity": 0, "color": "black", "weight": 2},
).add_to(m)

folium.LayerControl(collapsed=False).add_to(m)

MAP_FILE = PROJECT_DIR / "TamilNadu_FireMap.html"
m.save(str(MAP_FILE))
print("Saved:", MAP_FILE)


# --- SUMMARY ---------------------------------------------------------

print("\n" + "=" * 70)
print("PIPELINE COMPLETE")
print("=" * 70)
print("\nTamil Nadu detections classified:", f"{len(features_out):,}")
print("\nPredicted class distribution:")
print(features_out["predicted_class"].value_counts())
print("\nOutput files:")
print("1.", PHASE_FILE)
print("2.", GEOJSON_FILE)
print("3.", MAP_FILE)

# --- PATCH for Cell 12: better verification links + columns --------
#
# Fixes "empty land" confusion:
#   1. Default Google Maps links open at a wide, non-satellite zoom.
#      This switches to a close-in satellite/hybrid view.
#   2. Adds a second link showing BOTH the fire point and its matched
#      OSM facility on one map, so you can see the actual offset
#      distance instead of guessing from one point alone.
#   3. Surfaces facility match quality as its own column, so you can
#      sort/filter by "how good is this match" instead of relying on
#      eyeballing a possibly-outdated satellite photo.
#
# Run this instead of (or as a replacement block within) Cell 12.
# ---------------------------------------------------------------

def make_satellite_link(lat, lon, zoom=17):
    """Close-in satellite/hybrid view, much easier to actually see structures."""
    return f"https://www.google.com/maps/@{lat},{lon},{zoom}z/data=!3m1!1e3"


def make_dual_marker_link(fire_lat, fire_lon, facility_lat, facility_lon):
    """Shows the fire point and its matched facility as two markers,
    so you can see the real spatial relationship instead of guessing."""
    return (
        "https://www.google.com/maps/dir/?api=1"
        f"&origin={fire_lat},{fire_lon}"
        f"&destination={facility_lat},{facility_lon}"
        "&travelmode=walking"
    )


# Pull facility lat/lon back in (they exist in osm_df, joined by osm_id)
osm_lookup = osm_df.set_index("osm_id")[["latitude", "longitude"]].rename(
    columns={"latitude": "facility_latitude", "longitude": "facility_longitude"}
)

review_df = review_df.merge(
    features[["osm_id"]].join(osm_lookup, on="osm_id") if "osm_id" in features.columns else pd.DataFrame(),
    left_index=False, right_index=False, how="left"
) if "osm_id" in features.columns else review_df

# Simpler, robust version: rebuild directly from features (has osm_id from the join)
if "osm_id" in features.columns:
    review_df = review_df.reset_index(drop=True)
    fac_coords = features[["osm_id"]].reset_index(drop=True).join(osm_lookup, on="osm_id")
    review_df["facility_latitude"] = fac_coords["facility_latitude"]
    review_df["facility_longitude"] = fac_coords["facility_longitude"]

review_df["satellite_view_link"] = review_df.apply(
    lambda r: make_satellite_link(r["latitude"], r["longitude"]), axis=1
)

review_df["fire_vs_facility_link"] = review_df.apply(
    lambda r: make_dual_marker_link(
        r["latitude"], r["longitude"], r["facility_latitude"], r["facility_longitude"]
    ) if pd.notna(r.get("facility_latitude")) else "No matched facility",
    axis=1,
)

# Explicit match-quality tiering, so you can sort instead of eyeball
def match_quality(distance_km):
    if pd.isna(distance_km):
        return "No facility matched"
    if distance_km <= 0.5:
        return "Very close (<=500m) — should visually align"
    if distance_km <= 2.0:
        return "Near (<=2km) — may be offset in imagery"
    return "Far (>2km) — not actually a strong match"

review_df["match_quality"] = review_df["distance_to_facility_km"].apply(match_quality)

print("\nMatch quality breakdown (all predictions):")
print(review_df["match_quality"].value_counts())

print(
    "\nReading tip: for 'Industrial Fire' and 'Persistent Thermal Source' rows, "
    "check 'match_quality' FIRST. If most of them fall in 'Far (>2km)', the "
    "2000m threshold in the weak-label rule is too loose and should be tightened "
    "(e.g. to 1000m) rather than concluding the imagery is wrong. If most are "
    "'Very close' but still look empty on the satellite link, that's most likely "
    "the stale-imagery-date issue, not a matching problem."
)

# Re-export with the new columns and links
REVIEW_FILE_V2 = PROJECT_DIR / "SpotCheck_Review_v2.xlsx"

EXTRA_COLS = ["satellite_view_link", "fire_vs_facility_link", "match_quality"]
sheets_v2 = {}

for cls in review_df["predicted_class"].dropna().unique():
    class_df = review_df[review_df["predicted_class"] == cls].sort_values(
        "predicted_class_confidence", ascending=False
    )
    top = class_df.head(15)
    bottom = class_df.tail(10)
    combined = pd.concat([top, bottom]).drop_duplicates()
    sheets_v2[cls] = combined

with pd.ExcelWriter(REVIEW_FILE_V2, engine="openpyxl") as writer:
    for cls, df in sheets_v2.items():
        safe_name = "".join(c for c in cls if c.isalnum() or c in " _-")[:31]
        df.to_excel(writer, sheet_name=safe_name, index=False)

    from openpyxl.utils import get_column_letter

    for sheet_name in writer.sheets:
        ws = writer.sheets[sheet_name]
        header = [cell.value for cell in ws[1]]
        for link_col in ["google_maps_link", "satellite_view_link", "fire_vs_facility_link"]:
            if link_col in header:
                col_idx = header.index(link_col) + 1
                col_letter = get_column_letter(col_idx)
                for row in range(2, ws.max_row + 1):
                    cell = ws[f"{col_letter}{row}"]
                    if cell.value and str(cell.value).startswith("http"):
                        cell.hyperlink = cell.value
                        cell.style = "Hyperlink"

print("\nSaved:", REVIEW_FILE_V2)
print("New columns: satellite_view_link (zoomed-in), fire_vs_facility_link ")
print("(shows both points), match_quality (sort by this first).")